[package]
name = "openmicro"
version = "0.1.0"
license = "MIT"

[design]
top = "OpenMicro"

[dependencies]
"@st/stm32" = "0.1.0"
connectors = "0.1.0"
diode = "0.1.0"
esd = "0.1.0"
ldo = "0.1.0"
led = "0.1.0"
osc = "0.1.0"
passive = "0.2.0"
std = "0.3.0"
usb = "0.1.0"
