[workspace]
members = [
    "crates/cohdl-syntax",
    "crates/cohdl-parser",
    "crates/cohdl-sema",
    "crates/cohdl-drc",
    "crates/cohdl-codegen-kicad",
    "crates/cohdl-lsp",
    "crates/cohdl-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/conol/cohdl"

[workspace.dependencies]
pest = "2.7"
pest_derive = "2.7"
