[package]
name = "sf32-miniboard"
version = "0.1.0"
license = "MIT"

[design]
top = "SF32MiniBoard"

[dependencies]
"@contrib/sf32" = "0.1.0"
"@contrib/flash" = "0.1.0"
"@contrib/imu" = "0.1.0"
"@contrib/env" = "0.1.0"
"@contrib/usb-uart" = "0.1.0"
"@contrib/ldo" = "0.1.0"
"@contrib/sd-card" = "0.1.0"
"@contrib/lora" = "0.1.0"
qfn = "0.1.0"
std = "0.3.0"
