[package]
name = "sf32-miniboard"
version = "0.1.0"
license = "MIT"

[design]
top = "SF32MiniBoard"

[dependencies]
"@contrib/env" = "0.1.0"
"@contrib/imu" = "0.1.0"
"@contrib/ldo" = "0.1.0"
"@contrib/level-shifter" = "0.1.0"
"@richtek/dcdc" = "0.1.2"
"@sifli/sf32" = "0.1.0"
connectors = "0.1.1"
esd = "0.1.0"
flash = "0.1.3"
load-switch = "0.1.0"
misc = "0.1.1"
osc = "0.1.1"
passive = "0.2.1"
qfn = "0.2.0"
soic = "0.1.0"
std = "0.3.0"
usb = "0.1.1"
