[package]
name = "rpi-pico2"
version = "0.1.0"
license = "MIT"

[design]
top = "Pico2"

[dependencies]
"@raspberrypi/mcu" = "0.1.2"
"@richtek/dcdc" = "0.1.2"
connectors = "0.1.1"
diode = "0.1.0"
esd = "0.1.0"
flash = "0.1.3"
led = "0.1.1"
mosfet = "0.1.0"
osc = "0.1.1"
passive = "0.2.1"
qfn = "0.2.0"
soic = "0.2.0"
std = "0.3.0"
usb = "0.1.1"
