#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 43
#define LARGE_STATE_COUNT 38
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 7

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_COLON = 2,
  anon_sym_COMMA = 3,
  anon_sym_DOT = 4,
  anon_sym_COLON_COLON = 5,
  anon_sym_DOT_DOT_EQ = 6,
  anon_sym_LT = 7,
  anon_sym_GT = 8,
  anon_sym_EQ = 9,
  anon_sym_SEMI = 10,
  anon_sym_device = 11,
  anon_sym_trait = 12,
  anon_sym_part = 13,
  anon_sym_fn = 14,
  anon_sym_design = 15,
  anon_sym_subdesign = 16,
  anon_sym_footprint = 17,
  anon_sym_pad = 18,
  anon_sym_use = 19,
  anon_sym_impl = 20,
  anon_sym_for = 21,
  anon_sym_inst = 22,
  anon_sym_net = 23,
  anon_sym_pub = 24,
  sym_comment = 25,
  sym_string = 26,
  sym_unit_literal = 27,
  sym_number = 28,
  sym_wildcard = 29,
  anon_sym_POUND_LBRACK = 30,
  anon_sym_RBRACK = 31,
  anon_sym_LBRACE = 32,
  anon_sym_RBRACE = 33,
  anon_sym_LPAREN = 34,
  anon_sym_RPAREN = 35,
  anon_sym_LBRACK = 36,
  sym_source_file = 37,
  sym__node = 38,
  sym__keyword_fallback = 39,
  sym_declaration = 40,
  sym_use_declaration = 41,
  sym_impl_declaration = 42,
  sym_inst_statement = 43,
  sym_net_statement = 44,
  sym_pad_placement = 45,
  sym_path = 46,
  sym_attribute = 47,
  sym_block = 48,
  sym_parens = 49,
  sym_brackets = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_path_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_DOT_DOT_EQ] = "..=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_device] = "device",
  [anon_sym_trait] = "trait",
  [anon_sym_part] = "part",
  [anon_sym_fn] = "fn",
  [anon_sym_design] = "design",
  [anon_sym_subdesign] = "subdesign",
  [anon_sym_footprint] = "footprint",
  [anon_sym_pad] = "pad",
  [anon_sym_use] = "use",
  [anon_sym_impl] = "impl",
  [anon_sym_for] = "for",
  [anon_sym_inst] = "inst",
  [anon_sym_net] = "net",
  [anon_sym_pub] = "pub",
  [sym_comment] = "comment",
  [sym_string] = "string",
  [sym_unit_literal] = "unit_literal",
  [sym_number] = "number",
  [sym_wildcard] = "wildcard",
  [anon_sym_POUND_LBRACK] = "#[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [sym_source_file] = "source_file",
  [sym__node] = "_node",
  [sym__keyword_fallback] = "_keyword_fallback",
  [sym_declaration] = "declaration",
  [sym_use_declaration] = "use_declaration",
  [sym_impl_declaration] = "impl_declaration",
  [sym_inst_statement] = "inst_statement",
  [sym_net_statement] = "net_statement",
  [sym_pad_placement] = "pad_placement",
  [sym_path] = "path",
  [sym_attribute] = "attribute",
  [sym_block] = "block",
  [sym_parens] = "parens",
  [sym_brackets] = "brackets",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_DOT_DOT_EQ] = anon_sym_DOT_DOT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_device] = anon_sym_device,
  [anon_sym_trait] = anon_sym_trait,
  [anon_sym_part] = anon_sym_part,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_design] = anon_sym_design,
  [anon_sym_subdesign] = anon_sym_subdesign,
  [anon_sym_footprint] = anon_sym_footprint,
  [anon_sym_pad] = anon_sym_pad,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_impl] = anon_sym_impl,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_inst] = anon_sym_inst,
  [anon_sym_net] = anon_sym_net,
  [anon_sym_pub] = anon_sym_pub,
  [sym_comment] = sym_comment,
  [sym_string] = sym_string,
  [sym_unit_literal] = sym_unit_literal,
  [sym_number] = sym_number,
  [sym_wildcard] = sym_wildcard,
  [anon_sym_POUND_LBRACK] = anon_sym_POUND_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [sym_source_file] = sym_source_file,
  [sym__node] = sym__node,
  [sym__keyword_fallback] = sym__keyword_fallback,
  [sym_declaration] = sym_declaration,
  [sym_use_declaration] = sym_use_declaration,
  [sym_impl_declaration] = sym_impl_declaration,
  [sym_inst_statement] = sym_inst_statement,
  [sym_net_statement] = sym_net_statement,
  [sym_pad_placement] = sym_pad_placement,
  [sym_path] = sym_path,
  [sym_attribute] = sym_attribute,
  [sym_block] = sym_block,
  [sym_parens] = sym_parens,
  [sym_brackets] = sym_brackets,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_device] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trait] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_part] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_design] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_subdesign] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_footprint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pad] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_impl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inst] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_net] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pub] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_unit_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym__keyword_fallback] = {
    .visible = false,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_use_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_impl_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_inst_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_net_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_pad_placement] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_parens] = {
    .visible = true,
    .named = true,
  },
  [sym_brackets] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_device = 1,
  field_kind = 2,
  field_name = 3,
  field_number = 4,
  field_path = 5,
  field_trait = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_device] = "device",
  [field_kind] = "kind",
  [field_name] = "name",
  [field_number] = "number",
  [field_path] = "path",
  [field_trait] = "trait",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_kind, 0},
    {field_name, 1},
  [2] =
    {field_number, 1},
  [3] =
    {field_path, 1},
  [4] =
    {field_name, 1},
  [5] =
    {field_kind, 1},
    {field_name, 2},
  [7] =
    {field_device, 3},
    {field_trait, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 1,
        '#', 6,
        '(', 34,
        ')', 35,
        ',', 14,
        '-', 9,
        '.', 15,
        '/', 2,
        ':', 13,
        ';', 21,
        '<', 18,
        '=', 20,
        '>', 19,
        '[', 36,
        ']', 31,
        '{', 32,
        '}', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        'H', 27,
        'm', 26,
        'o', 7,
        '%', 25,
        'A', 25,
        'C', 25,
        'F', 25,
        'V', 25,
        'W', 25,
        's', 25,
      );
      END_STATE();
    case 5:
      ADVANCE_MAP(
        'H', 27,
        'm', 8,
        'o', 7,
        '%', 25,
        'A', 25,
        'C', 25,
        'F', 25,
        'V', 25,
        'W', 25,
        's', 25,
      );
      END_STATE();
    case 6:
      if (lookahead == '[') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == 'h') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(3);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_unit_literal);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_unit_literal);
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_unit_literal);
      if (lookahead == 'z') ADVANCE(25);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      ADVANCE_MAP(
        '.', 10,
        'H', 27,
        'm', 4,
        'o', 7,
        'G', 5,
        'M', 5,
        'k', 5,
        'n', 5,
        'p', 5,
        'u', 5,
        '%', 25,
        'A', 25,
        'C', 25,
        'F', 25,
        'V', 25,
        'W', 25,
        's', 25,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      ADVANCE_MAP(
        'H', 27,
        'm', 4,
        'o', 7,
        'G', 5,
        'M', 5,
        'k', 5,
        'n', 5,
        'p', 5,
        'u', 5,
        '%', 25,
        'A', 25,
        'C', 25,
        'F', 25,
        'V', 25,
        'W', 25,
        's', 25,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        '_', 1,
        'd', 2,
        'f', 3,
        'i', 4,
        'n', 5,
        'p', 6,
        's', 7,
        't', 8,
        'u', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(sym_wildcard);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(11);
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'm') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(21);
      if (lookahead == 'v') ADVANCE(22);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(23);
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(28);
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'b') ADVANCE(30);
      END_STATE();
    case 18:
      if (lookahead == 'b') ADVANCE(31);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_net);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_pad);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_pub);
      END_STATE();
    case 31:
      if (lookahead == 'd') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 34:
      if (lookahead == 'g') ADVANCE(42);
      END_STATE();
    case 35:
      if (lookahead == 'c') ADVANCE(43);
      END_STATE();
    case 36:
      if (lookahead == 'p') ADVANCE(44);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_impl);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_inst);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_part);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(50);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_trait);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_design);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_device);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 52:
      if (lookahead == 'g') ADVANCE(54);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_footprint);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_subdesign);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_device] = ACTIONS(1),
    [anon_sym_trait] = ACTIONS(1),
    [anon_sym_part] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_design] = ACTIONS(1),
    [anon_sym_subdesign] = ACTIONS(1),
    [anon_sym_footprint] = ACTIONS(1),
    [anon_sym_pad] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_impl] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_inst] = ACTIONS(1),
    [anon_sym_net] = ACTIONS(1),
    [anon_sym_pub] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(1),
    [sym_unit_literal] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [anon_sym_POUND_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(42),
    [sym__node] = STATE(9),
    [sym__keyword_fallback] = STATE(9),
    [sym_declaration] = STATE(9),
    [sym_use_declaration] = STATE(9),
    [sym_impl_declaration] = STATE(9),
    [sym_inst_statement] = STATE(9),
    [sym_net_statement] = STATE(9),
    [sym_pad_placement] = STATE(9),
    [sym_attribute] = STATE(9),
    [sym_block] = STATE(9),
    [sym_parens] = STATE(9),
    [sym_brackets] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(7),
    [anon_sym_COLON_COLON] = ACTIONS(9),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_device] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_part] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_design] = ACTIONS(11),
    [anon_sym_subdesign] = ACTIONS(11),
    [anon_sym_footprint] = ACTIONS(11),
    [anon_sym_pad] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(7),
    [anon_sym_inst] = ACTIONS(19),
    [anon_sym_net] = ACTIONS(21),
    [anon_sym_pub] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(9),
    [sym_unit_literal] = ACTIONS(9),
    [sym_number] = ACTIONS(7),
    [sym_wildcard] = ACTIONS(7),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
  },
  [2] = {
    [sym__node] = STATE(2),
    [sym__keyword_fallback] = STATE(2),
    [sym_declaration] = STATE(2),
    [sym_use_declaration] = STATE(2),
    [sym_impl_declaration] = STATE(2),
    [sym_inst_statement] = STATE(2),
    [sym_net_statement] = STATE(2),
    [sym_pad_placement] = STATE(2),
    [sym_attribute] = STATE(2),
    [sym_block] = STATE(2),
    [sym_parens] = STATE(2),
    [sym_brackets] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_COLON] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(38),
    [anon_sym_DOT] = ACTIONS(35),
    [anon_sym_COLON_COLON] = ACTIONS(38),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(38),
    [anon_sym_LT] = ACTIONS(38),
    [anon_sym_GT] = ACTIONS(38),
    [anon_sym_EQ] = ACTIONS(38),
    [anon_sym_SEMI] = ACTIONS(38),
    [anon_sym_device] = ACTIONS(41),
    [anon_sym_trait] = ACTIONS(41),
    [anon_sym_part] = ACTIONS(41),
    [anon_sym_fn] = ACTIONS(41),
    [anon_sym_design] = ACTIONS(41),
    [anon_sym_subdesign] = ACTIONS(41),
    [anon_sym_footprint] = ACTIONS(41),
    [anon_sym_pad] = ACTIONS(44),
    [anon_sym_use] = ACTIONS(47),
    [anon_sym_impl] = ACTIONS(50),
    [anon_sym_for] = ACTIONS(35),
    [anon_sym_inst] = ACTIONS(53),
    [anon_sym_net] = ACTIONS(56),
    [anon_sym_pub] = ACTIONS(59),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(38),
    [sym_unit_literal] = ACTIONS(38),
    [sym_number] = ACTIONS(35),
    [sym_wildcard] = ACTIONS(35),
    [anon_sym_POUND_LBRACK] = ACTIONS(62),
    [anon_sym_RBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(65),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(68),
    [anon_sym_RPAREN] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(71),
  },
  [3] = {
    [sym__node] = STATE(2),
    [sym__keyword_fallback] = STATE(2),
    [sym_declaration] = STATE(2),
    [sym_use_declaration] = STATE(2),
    [sym_impl_declaration] = STATE(2),
    [sym_inst_statement] = STATE(2),
    [sym_net_statement] = STATE(2),
    [sym_pad_placement] = STATE(2),
    [sym_attribute] = STATE(2),
    [sym_block] = STATE(2),
    [sym_parens] = STATE(2),
    [sym_brackets] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(74),
    [anon_sym_COLON] = ACTIONS(74),
    [anon_sym_COMMA] = ACTIONS(76),
    [anon_sym_DOT] = ACTIONS(74),
    [anon_sym_COLON_COLON] = ACTIONS(76),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(76),
    [anon_sym_LT] = ACTIONS(76),
    [anon_sym_GT] = ACTIONS(76),
    [anon_sym_EQ] = ACTIONS(76),
    [anon_sym_SEMI] = ACTIONS(76),
    [anon_sym_device] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_part] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_design] = ACTIONS(11),
    [anon_sym_subdesign] = ACTIONS(11),
    [anon_sym_footprint] = ACTIONS(11),
    [anon_sym_pad] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(74),
    [anon_sym_inst] = ACTIONS(19),
    [anon_sym_net] = ACTIONS(21),
    [anon_sym_pub] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(76),
    [sym_unit_literal] = ACTIONS(76),
    [sym_number] = ACTIONS(74),
    [sym_wildcard] = ACTIONS(74),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(78),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
  },
  [4] = {
    [sym__node] = STATE(2),
    [sym__keyword_fallback] = STATE(2),
    [sym_declaration] = STATE(2),
    [sym_use_declaration] = STATE(2),
    [sym_impl_declaration] = STATE(2),
    [sym_inst_statement] = STATE(2),
    [sym_net_statement] = STATE(2),
    [sym_pad_placement] = STATE(2),
    [sym_attribute] = STATE(2),
    [sym_block] = STATE(2),
    [sym_parens] = STATE(2),
    [sym_brackets] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(74),
    [anon_sym_COLON] = ACTIONS(74),
    [anon_sym_COMMA] = ACTIONS(76),
    [anon_sym_DOT] = ACTIONS(74),
    [anon_sym_COLON_COLON] = ACTIONS(76),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(76),
    [anon_sym_LT] = ACTIONS(76),
    [anon_sym_GT] = ACTIONS(76),
    [anon_sym_EQ] = ACTIONS(76),
    [anon_sym_SEMI] = ACTIONS(76),
    [anon_sym_device] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_part] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_design] = ACTIONS(11),
    [anon_sym_subdesign] = ACTIONS(11),
    [anon_sym_footprint] = ACTIONS(11),
    [anon_sym_pad] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(74),
    [anon_sym_inst] = ACTIONS(19),
    [anon_sym_net] = ACTIONS(21),
    [anon_sym_pub] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(76),
    [sym_unit_literal] = ACTIONS(76),
    [sym_number] = ACTIONS(74),
    [sym_wildcard] = ACTIONS(74),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(80),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
  },
  [5] = {
    [sym__node] = STATE(4),
    [sym__keyword_fallback] = STATE(4),
    [sym_declaration] = STATE(4),
    [sym_use_declaration] = STATE(4),
    [sym_impl_declaration] = STATE(4),
    [sym_inst_statement] = STATE(4),
    [sym_net_statement] = STATE(4),
    [sym_pad_placement] = STATE(4),
    [sym_attribute] = STATE(4),
    [sym_block] = STATE(4),
    [sym_parens] = STATE(4),
    [sym_brackets] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(82),
    [anon_sym_COLON] = ACTIONS(82),
    [anon_sym_COMMA] = ACTIONS(84),
    [anon_sym_DOT] = ACTIONS(82),
    [anon_sym_COLON_COLON] = ACTIONS(84),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(84),
    [anon_sym_LT] = ACTIONS(84),
    [anon_sym_GT] = ACTIONS(84),
    [anon_sym_EQ] = ACTIONS(84),
    [anon_sym_SEMI] = ACTIONS(84),
    [anon_sym_device] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_part] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_design] = ACTIONS(11),
    [anon_sym_subdesign] = ACTIONS(11),
    [anon_sym_footprint] = ACTIONS(11),
    [anon_sym_pad] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(82),
    [anon_sym_inst] = ACTIONS(19),
    [anon_sym_net] = ACTIONS(21),
    [anon_sym_pub] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(84),
    [sym_unit_literal] = ACTIONS(84),
    [sym_number] = ACTIONS(82),
    [sym_wildcard] = ACTIONS(82),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(86),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
  },
  [6] = {
    [sym__node] = STATE(3),
    [sym__keyword_fallback] = STATE(3),
    [sym_declaration] = STATE(3),
    [sym_use_declaration] = STATE(3),
    [sym_impl_declaration] = STATE(3),
    [sym_inst_statement] = STATE(3),
    [sym_net_statement] = STATE(3),
    [sym_pad_placement] = STATE(3),
    [sym_attribute] = STATE(3),
    [sym_block] = STATE(3),
    [sym_parens] = STATE(3),
    [sym_brackets] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(88),
    [anon_sym_COLON] = ACTIONS(88),
    [anon_sym_COMMA] = ACTIONS(90),
    [anon_sym_DOT] = ACTIONS(88),
    [anon_sym_COLON_COLON] = ACTIONS(90),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(90),
    [anon_sym_LT] = ACTIONS(90),
    [anon_sym_GT] = ACTIONS(90),
    [anon_sym_EQ] = ACTIONS(90),
    [anon_sym_SEMI] = ACTIONS(90),
    [anon_sym_device] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_part] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_design] = ACTIONS(11),
    [anon_sym_subdesign] = ACTIONS(11),
    [anon_sym_footprint] = ACTIONS(11),
    [anon_sym_pad] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(88),
    [anon_sym_inst] = ACTIONS(19),
    [anon_sym_net] = ACTIONS(21),
    [anon_sym_pub] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(90),
    [sym_unit_literal] = ACTIONS(90),
    [sym_number] = ACTIONS(88),
    [sym_wildcard] = ACTIONS(88),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(92),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
  },
  [7] = {
    [sym__node] = STATE(10),
    [sym__keyword_fallback] = STATE(10),
    [sym_declaration] = STATE(10),
    [sym_use_declaration] = STATE(10),
    [sym_impl_declaration] = STATE(10),
    [sym_inst_statement] = STATE(10),
    [sym_net_statement] = STATE(10),
    [sym_pad_placement] = STATE(10),
    [sym_attribute] = STATE(10),
    [sym_block] = STATE(10),
    [sym_parens] = STATE(10),
    [sym_brackets] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [sym_identifier] = ACTIONS(94),
    [anon_sym_COLON] = ACTIONS(94),
    [anon_sym_COMMA] = ACTIONS(96),
    [anon_sym_DOT] = ACTIONS(94),
    [anon_sym_COLON_COLON] = ACTIONS(96),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(96),
    [anon_sym_LT] = ACTIONS(96),
    [anon_sym_GT] = ACTIONS(96),
    [anon_sym_EQ] = ACTIONS(96),
    [anon_sym_SEMI] = ACTIONS(96),
    [anon_sym_device] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_part] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_design] = ACTIONS(11),
    [anon_sym_subdesign] = ACTIONS(11),
    [anon_sym_footprint] = ACTIONS(11),
    [anon_sym_pad] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(94),
    [anon_sym_inst] = ACTIONS(19),
    [anon_sym_net] = ACTIONS(21),
    [anon_sym_pub] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(96),
    [sym_unit_literal] = ACTIONS(96),
    [sym_number] = ACTIONS(94),
    [sym_wildcard] = ACTIONS(94),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(98),
    [anon_sym_LBRACK] = ACTIONS(31),
  },
  [8] = {
    [sym__node] = STATE(11),
    [sym__keyword_fallback] = STATE(11),
    [sym_declaration] = STATE(11),
    [sym_use_declaration] = STATE(11),
    [sym_impl_declaration] = STATE(11),
    [sym_inst_statement] = STATE(11),
    [sym_net_statement] = STATE(11),
    [sym_pad_placement] = STATE(11),
    [sym_attribute] = STATE(11),
    [sym_block] = STATE(11),
    [sym_parens] = STATE(11),
    [sym_brackets] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [sym_identifier] = ACTIONS(100),
    [anon_sym_COLON] = ACTIONS(100),
    [anon_sym_COMMA] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(100),
    [anon_sym_COLON_COLON] = ACTIONS(102),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(102),
    [anon_sym_LT] = ACTIONS(102),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_EQ] = ACTIONS(102),
    [anon_sym_SEMI] = ACTIONS(102),
    [anon_sym_device] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_part] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_design] = ACTIONS(11),
    [anon_sym_subdesign] = ACTIONS(11),
    [anon_sym_footprint] = ACTIONS(11),
    [anon_sym_pad] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(100),
    [anon_sym_inst] = ACTIONS(19),
    [anon_sym_net] = ACTIONS(21),
    [anon_sym_pub] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(102),
    [sym_unit_literal] = ACTIONS(102),
    [sym_number] = ACTIONS(100),
    [sym_wildcard] = ACTIONS(100),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
  },
  [9] = {
    [sym__node] = STATE(2),
    [sym__keyword_fallback] = STATE(2),
    [sym_declaration] = STATE(2),
    [sym_use_declaration] = STATE(2),
    [sym_impl_declaration] = STATE(2),
    [sym_inst_statement] = STATE(2),
    [sym_net_statement] = STATE(2),
    [sym_pad_placement] = STATE(2),
    [sym_attribute] = STATE(2),
    [sym_block] = STATE(2),
    [sym_parens] = STATE(2),
    [sym_brackets] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(106),
    [sym_identifier] = ACTIONS(74),
    [anon_sym_COLON] = ACTIONS(74),
    [anon_sym_COMMA] = ACTIONS(76),
    [anon_sym_DOT] = ACTIONS(74),
    [anon_sym_COLON_COLON] = ACTIONS(76),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(76),
    [anon_sym_LT] = ACTIONS(76),
    [anon_sym_GT] = ACTIONS(76),
    [anon_sym_EQ] = ACTIONS(76),
    [anon_sym_SEMI] = ACTIONS(76),
    [anon_sym_device] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_part] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_design] = ACTIONS(11),
    [anon_sym_subdesign] = ACTIONS(11),
    [anon_sym_footprint] = ACTIONS(11),
    [anon_sym_pad] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(74),
    [anon_sym_inst] = ACTIONS(19),
    [anon_sym_net] = ACTIONS(21),
    [anon_sym_pub] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(76),
    [sym_unit_literal] = ACTIONS(76),
    [sym_number] = ACTIONS(74),
    [sym_wildcard] = ACTIONS(74),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
  },
  [10] = {
    [sym__node] = STATE(2),
    [sym__keyword_fallback] = STATE(2),
    [sym_declaration] = STATE(2),
    [sym_use_declaration] = STATE(2),
    [sym_impl_declaration] = STATE(2),
    [sym_inst_statement] = STATE(2),
    [sym_net_statement] = STATE(2),
    [sym_pad_placement] = STATE(2),
    [sym_attribute] = STATE(2),
    [sym_block] = STATE(2),
    [sym_parens] = STATE(2),
    [sym_brackets] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(74),
    [anon_sym_COLON] = ACTIONS(74),
    [anon_sym_COMMA] = ACTIONS(76),
    [anon_sym_DOT] = ACTIONS(74),
    [anon_sym_COLON_COLON] = ACTIONS(76),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(76),
    [anon_sym_LT] = ACTIONS(76),
    [anon_sym_GT] = ACTIONS(76),
    [anon_sym_EQ] = ACTIONS(76),
    [anon_sym_SEMI] = ACTIONS(76),
    [anon_sym_device] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_part] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_design] = ACTIONS(11),
    [anon_sym_subdesign] = ACTIONS(11),
    [anon_sym_footprint] = ACTIONS(11),
    [anon_sym_pad] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(74),
    [anon_sym_inst] = ACTIONS(19),
    [anon_sym_net] = ACTIONS(21),
    [anon_sym_pub] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(76),
    [sym_unit_literal] = ACTIONS(76),
    [sym_number] = ACTIONS(74),
    [sym_wildcard] = ACTIONS(74),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(108),
    [anon_sym_LBRACK] = ACTIONS(31),
  },
  [11] = {
    [sym__node] = STATE(2),
    [sym__keyword_fallback] = STATE(2),
    [sym_declaration] = STATE(2),
    [sym_use_declaration] = STATE(2),
    [sym_impl_declaration] = STATE(2),
    [sym_inst_statement] = STATE(2),
    [sym_net_statement] = STATE(2),
    [sym_pad_placement] = STATE(2),
    [sym_attribute] = STATE(2),
    [sym_block] = STATE(2),
    [sym_parens] = STATE(2),
    [sym_brackets] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(74),
    [anon_sym_COLON] = ACTIONS(74),
    [anon_sym_COMMA] = ACTIONS(76),
    [anon_sym_DOT] = ACTIONS(74),
    [anon_sym_COLON_COLON] = ACTIONS(76),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(76),
    [anon_sym_LT] = ACTIONS(76),
    [anon_sym_GT] = ACTIONS(76),
    [anon_sym_EQ] = ACTIONS(76),
    [anon_sym_SEMI] = ACTIONS(76),
    [anon_sym_device] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_part] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(11),
    [anon_sym_design] = ACTIONS(11),
    [anon_sym_subdesign] = ACTIONS(11),
    [anon_sym_footprint] = ACTIONS(11),
    [anon_sym_pad] = ACTIONS(13),
    [anon_sym_use] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(74),
    [anon_sym_inst] = ACTIONS(19),
    [anon_sym_net] = ACTIONS(21),
    [anon_sym_pub] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(76),
    [sym_unit_literal] = ACTIONS(76),
    [sym_number] = ACTIONS(74),
    [sym_wildcard] = ACTIONS(74),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(110),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(31),
  },
  [12] = {
    [sym_path] = STATE(39),
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_identifier] = ACTIONS(114),
    [anon_sym_COLON] = ACTIONS(116),
    [anon_sym_COMMA] = ACTIONS(112),
    [anon_sym_DOT] = ACTIONS(116),
    [anon_sym_COLON_COLON] = ACTIONS(112),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(112),
    [anon_sym_LT] = ACTIONS(112),
    [anon_sym_GT] = ACTIONS(112),
    [anon_sym_EQ] = ACTIONS(112),
    [anon_sym_SEMI] = ACTIONS(112),
    [anon_sym_device] = ACTIONS(116),
    [anon_sym_trait] = ACTIONS(116),
    [anon_sym_part] = ACTIONS(116),
    [anon_sym_fn] = ACTIONS(116),
    [anon_sym_design] = ACTIONS(116),
    [anon_sym_subdesign] = ACTIONS(116),
    [anon_sym_footprint] = ACTIONS(116),
    [anon_sym_pad] = ACTIONS(116),
    [anon_sym_use] = ACTIONS(116),
    [anon_sym_impl] = ACTIONS(116),
    [anon_sym_for] = ACTIONS(116),
    [anon_sym_inst] = ACTIONS(116),
    [anon_sym_net] = ACTIONS(116),
    [anon_sym_pub] = ACTIONS(116),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(112),
    [sym_unit_literal] = ACTIONS(112),
    [sym_number] = ACTIONS(116),
    [sym_wildcard] = ACTIONS(116),
    [anon_sym_POUND_LBRACK] = ACTIONS(112),
    [anon_sym_RBRACK] = ACTIONS(112),
    [anon_sym_LBRACE] = ACTIONS(112),
    [anon_sym_RBRACE] = ACTIONS(112),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(112),
    [anon_sym_LBRACK] = ACTIONS(112),
  },
  [13] = {
    [aux_sym_path_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(118),
    [sym_identifier] = ACTIONS(120),
    [anon_sym_COLON] = ACTIONS(120),
    [anon_sym_COMMA] = ACTIONS(118),
    [anon_sym_DOT] = ACTIONS(120),
    [anon_sym_COLON_COLON] = ACTIONS(122),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(118),
    [anon_sym_LT] = ACTIONS(118),
    [anon_sym_GT] = ACTIONS(118),
    [anon_sym_EQ] = ACTIONS(118),
    [anon_sym_SEMI] = ACTIONS(118),
    [anon_sym_device] = ACTIONS(120),
    [anon_sym_trait] = ACTIONS(120),
    [anon_sym_part] = ACTIONS(120),
    [anon_sym_fn] = ACTIONS(120),
    [anon_sym_design] = ACTIONS(120),
    [anon_sym_subdesign] = ACTIONS(120),
    [anon_sym_footprint] = ACTIONS(120),
    [anon_sym_pad] = ACTIONS(120),
    [anon_sym_use] = ACTIONS(120),
    [anon_sym_impl] = ACTIONS(120),
    [anon_sym_for] = ACTIONS(120),
    [anon_sym_inst] = ACTIONS(120),
    [anon_sym_net] = ACTIONS(120),
    [anon_sym_pub] = ACTIONS(120),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(118),
    [sym_unit_literal] = ACTIONS(118),
    [sym_number] = ACTIONS(120),
    [sym_wildcard] = ACTIONS(120),
    [anon_sym_POUND_LBRACK] = ACTIONS(118),
    [anon_sym_RBRACK] = ACTIONS(118),
    [anon_sym_LBRACE] = ACTIONS(118),
    [anon_sym_RBRACE] = ACTIONS(118),
    [anon_sym_LPAREN] = ACTIONS(118),
    [anon_sym_RPAREN] = ACTIONS(118),
    [anon_sym_LBRACK] = ACTIONS(118),
  },
  [14] = {
    [sym_path] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_identifier] = ACTIONS(114),
    [anon_sym_COLON] = ACTIONS(116),
    [anon_sym_COMMA] = ACTIONS(112),
    [anon_sym_DOT] = ACTIONS(116),
    [anon_sym_COLON_COLON] = ACTIONS(112),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(112),
    [anon_sym_LT] = ACTIONS(112),
    [anon_sym_GT] = ACTIONS(112),
    [anon_sym_EQ] = ACTIONS(112),
    [anon_sym_SEMI] = ACTIONS(112),
    [anon_sym_device] = ACTIONS(116),
    [anon_sym_trait] = ACTIONS(116),
    [anon_sym_part] = ACTIONS(116),
    [anon_sym_fn] = ACTIONS(116),
    [anon_sym_design] = ACTIONS(116),
    [anon_sym_subdesign] = ACTIONS(116),
    [anon_sym_footprint] = ACTIONS(116),
    [anon_sym_pad] = ACTIONS(116),
    [anon_sym_use] = ACTIONS(116),
    [anon_sym_impl] = ACTIONS(116),
    [anon_sym_for] = ACTIONS(116),
    [anon_sym_inst] = ACTIONS(116),
    [anon_sym_net] = ACTIONS(116),
    [anon_sym_pub] = ACTIONS(116),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(112),
    [sym_unit_literal] = ACTIONS(112),
    [sym_number] = ACTIONS(116),
    [sym_wildcard] = ACTIONS(116),
    [anon_sym_POUND_LBRACK] = ACTIONS(112),
    [anon_sym_RBRACK] = ACTIONS(112),
    [anon_sym_LBRACE] = ACTIONS(112),
    [anon_sym_RBRACE] = ACTIONS(112),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(112),
    [anon_sym_LBRACK] = ACTIONS(112),
  },
  [15] = {
    [aux_sym_path_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(124),
    [sym_identifier] = ACTIONS(126),
    [anon_sym_COLON] = ACTIONS(126),
    [anon_sym_COMMA] = ACTIONS(124),
    [anon_sym_DOT] = ACTIONS(126),
    [anon_sym_COLON_COLON] = ACTIONS(122),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(124),
    [anon_sym_LT] = ACTIONS(124),
    [anon_sym_GT] = ACTIONS(124),
    [anon_sym_EQ] = ACTIONS(124),
    [anon_sym_SEMI] = ACTIONS(124),
    [anon_sym_device] = ACTIONS(126),
    [anon_sym_trait] = ACTIONS(126),
    [anon_sym_part] = ACTIONS(126),
    [anon_sym_fn] = ACTIONS(126),
    [anon_sym_design] = ACTIONS(126),
    [anon_sym_subdesign] = ACTIONS(126),
    [anon_sym_footprint] = ACTIONS(126),
    [anon_sym_pad] = ACTIONS(126),
    [anon_sym_use] = ACTIONS(126),
    [anon_sym_impl] = ACTIONS(126),
    [anon_sym_for] = ACTIONS(126),
    [anon_sym_inst] = ACTIONS(126),
    [anon_sym_net] = ACTIONS(126),
    [anon_sym_pub] = ACTIONS(126),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(124),
    [sym_unit_literal] = ACTIONS(124),
    [sym_number] = ACTIONS(126),
    [sym_wildcard] = ACTIONS(126),
    [anon_sym_POUND_LBRACK] = ACTIONS(124),
    [anon_sym_RBRACK] = ACTIONS(124),
    [anon_sym_LBRACE] = ACTIONS(124),
    [anon_sym_RBRACE] = ACTIONS(124),
    [anon_sym_LPAREN] = ACTIONS(124),
    [anon_sym_RPAREN] = ACTIONS(124),
    [anon_sym_LBRACK] = ACTIONS(124),
  },
  [16] = {
    [aux_sym_path_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(128),
    [sym_identifier] = ACTIONS(130),
    [anon_sym_COLON] = ACTIONS(130),
    [anon_sym_COMMA] = ACTIONS(128),
    [anon_sym_DOT] = ACTIONS(130),
    [anon_sym_COLON_COLON] = ACTIONS(132),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(128),
    [anon_sym_LT] = ACTIONS(128),
    [anon_sym_GT] = ACTIONS(128),
    [anon_sym_EQ] = ACTIONS(128),
    [anon_sym_SEMI] = ACTIONS(128),
    [anon_sym_device] = ACTIONS(130),
    [anon_sym_trait] = ACTIONS(130),
    [anon_sym_part] = ACTIONS(130),
    [anon_sym_fn] = ACTIONS(130),
    [anon_sym_design] = ACTIONS(130),
    [anon_sym_subdesign] = ACTIONS(130),
    [anon_sym_footprint] = ACTIONS(130),
    [anon_sym_pad] = ACTIONS(130),
    [anon_sym_use] = ACTIONS(130),
    [anon_sym_impl] = ACTIONS(130),
    [anon_sym_for] = ACTIONS(130),
    [anon_sym_inst] = ACTIONS(130),
    [anon_sym_net] = ACTIONS(130),
    [anon_sym_pub] = ACTIONS(130),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(128),
    [sym_unit_literal] = ACTIONS(128),
    [sym_number] = ACTIONS(130),
    [sym_wildcard] = ACTIONS(130),
    [anon_sym_POUND_LBRACK] = ACTIONS(128),
    [anon_sym_RBRACK] = ACTIONS(128),
    [anon_sym_LBRACE] = ACTIONS(128),
    [anon_sym_RBRACE] = ACTIONS(128),
    [anon_sym_LPAREN] = ACTIONS(128),
    [anon_sym_RPAREN] = ACTIONS(128),
    [anon_sym_LBRACK] = ACTIONS(128),
  },
  [17] = {
    [ts_builtin_sym_end] = ACTIONS(135),
    [sym_identifier] = ACTIONS(137),
    [anon_sym_COLON] = ACTIONS(137),
    [anon_sym_COMMA] = ACTIONS(135),
    [anon_sym_DOT] = ACTIONS(137),
    [anon_sym_COLON_COLON] = ACTIONS(135),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(135),
    [anon_sym_LT] = ACTIONS(135),
    [anon_sym_GT] = ACTIONS(135),
    [anon_sym_EQ] = ACTIONS(135),
    [anon_sym_SEMI] = ACTIONS(135),
    [anon_sym_device] = ACTIONS(137),
    [anon_sym_trait] = ACTIONS(137),
    [anon_sym_part] = ACTIONS(137),
    [anon_sym_fn] = ACTIONS(137),
    [anon_sym_design] = ACTIONS(137),
    [anon_sym_subdesign] = ACTIONS(137),
    [anon_sym_footprint] = ACTIONS(137),
    [anon_sym_pad] = ACTIONS(137),
    [anon_sym_use] = ACTIONS(137),
    [anon_sym_impl] = ACTIONS(137),
    [anon_sym_for] = ACTIONS(137),
    [anon_sym_inst] = ACTIONS(137),
    [anon_sym_net] = ACTIONS(137),
    [anon_sym_pub] = ACTIONS(137),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(135),
    [sym_unit_literal] = ACTIONS(135),
    [sym_number] = ACTIONS(137),
    [sym_wildcard] = ACTIONS(137),
    [anon_sym_POUND_LBRACK] = ACTIONS(135),
    [anon_sym_RBRACK] = ACTIONS(135),
    [anon_sym_LBRACE] = ACTIONS(135),
    [anon_sym_RBRACE] = ACTIONS(135),
    [anon_sym_LPAREN] = ACTIONS(135),
    [anon_sym_RPAREN] = ACTIONS(135),
    [anon_sym_LBRACK] = ACTIONS(135),
  },
  [18] = {
    [ts_builtin_sym_end] = ACTIONS(139),
    [sym_identifier] = ACTIONS(141),
    [anon_sym_COLON] = ACTIONS(141),
    [anon_sym_COMMA] = ACTIONS(139),
    [anon_sym_DOT] = ACTIONS(141),
    [anon_sym_COLON_COLON] = ACTIONS(139),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(139),
    [anon_sym_LT] = ACTIONS(139),
    [anon_sym_GT] = ACTIONS(139),
    [anon_sym_EQ] = ACTIONS(139),
    [anon_sym_SEMI] = ACTIONS(139),
    [anon_sym_device] = ACTIONS(141),
    [anon_sym_trait] = ACTIONS(141),
    [anon_sym_part] = ACTIONS(141),
    [anon_sym_fn] = ACTIONS(141),
    [anon_sym_design] = ACTIONS(141),
    [anon_sym_subdesign] = ACTIONS(141),
    [anon_sym_footprint] = ACTIONS(141),
    [anon_sym_pad] = ACTIONS(141),
    [anon_sym_use] = ACTIONS(141),
    [anon_sym_impl] = ACTIONS(141),
    [anon_sym_for] = ACTIONS(141),
    [anon_sym_inst] = ACTIONS(141),
    [anon_sym_net] = ACTIONS(141),
    [anon_sym_pub] = ACTIONS(141),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(139),
    [sym_unit_literal] = ACTIONS(139),
    [sym_number] = ACTIONS(141),
    [sym_wildcard] = ACTIONS(141),
    [anon_sym_POUND_LBRACK] = ACTIONS(139),
    [anon_sym_RBRACK] = ACTIONS(139),
    [anon_sym_LBRACE] = ACTIONS(139),
    [anon_sym_RBRACE] = ACTIONS(139),
    [anon_sym_LPAREN] = ACTIONS(139),
    [anon_sym_RPAREN] = ACTIONS(139),
    [anon_sym_LBRACK] = ACTIONS(139),
  },
  [19] = {
    [ts_builtin_sym_end] = ACTIONS(143),
    [sym_identifier] = ACTIONS(145),
    [anon_sym_COLON] = ACTIONS(145),
    [anon_sym_COMMA] = ACTIONS(143),
    [anon_sym_DOT] = ACTIONS(145),
    [anon_sym_COLON_COLON] = ACTIONS(143),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(143),
    [anon_sym_LT] = ACTIONS(143),
    [anon_sym_GT] = ACTIONS(143),
    [anon_sym_EQ] = ACTIONS(143),
    [anon_sym_SEMI] = ACTIONS(143),
    [anon_sym_device] = ACTIONS(145),
    [anon_sym_trait] = ACTIONS(145),
    [anon_sym_part] = ACTIONS(145),
    [anon_sym_fn] = ACTIONS(145),
    [anon_sym_design] = ACTIONS(145),
    [anon_sym_subdesign] = ACTIONS(145),
    [anon_sym_footprint] = ACTIONS(145),
    [anon_sym_pad] = ACTIONS(145),
    [anon_sym_use] = ACTIONS(145),
    [anon_sym_impl] = ACTIONS(145),
    [anon_sym_for] = ACTIONS(145),
    [anon_sym_inst] = ACTIONS(145),
    [anon_sym_net] = ACTIONS(145),
    [anon_sym_pub] = ACTIONS(145),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(143),
    [sym_unit_literal] = ACTIONS(143),
    [sym_number] = ACTIONS(145),
    [sym_wildcard] = ACTIONS(145),
    [anon_sym_POUND_LBRACK] = ACTIONS(143),
    [anon_sym_RBRACK] = ACTIONS(143),
    [anon_sym_LBRACE] = ACTIONS(143),
    [anon_sym_RBRACE] = ACTIONS(143),
    [anon_sym_LPAREN] = ACTIONS(143),
    [anon_sym_RPAREN] = ACTIONS(143),
    [anon_sym_LBRACK] = ACTIONS(143),
  },
  [20] = {
    [ts_builtin_sym_end] = ACTIONS(147),
    [sym_identifier] = ACTIONS(149),
    [anon_sym_COLON] = ACTIONS(149),
    [anon_sym_COMMA] = ACTIONS(147),
    [anon_sym_DOT] = ACTIONS(149),
    [anon_sym_COLON_COLON] = ACTIONS(147),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(147),
    [anon_sym_LT] = ACTIONS(147),
    [anon_sym_GT] = ACTIONS(147),
    [anon_sym_EQ] = ACTIONS(147),
    [anon_sym_SEMI] = ACTIONS(147),
    [anon_sym_device] = ACTIONS(149),
    [anon_sym_trait] = ACTIONS(149),
    [anon_sym_part] = ACTIONS(149),
    [anon_sym_fn] = ACTIONS(149),
    [anon_sym_design] = ACTIONS(149),
    [anon_sym_subdesign] = ACTIONS(149),
    [anon_sym_footprint] = ACTIONS(149),
    [anon_sym_pad] = ACTIONS(149),
    [anon_sym_use] = ACTIONS(149),
    [anon_sym_impl] = ACTIONS(149),
    [anon_sym_for] = ACTIONS(149),
    [anon_sym_inst] = ACTIONS(149),
    [anon_sym_net] = ACTIONS(149),
    [anon_sym_pub] = ACTIONS(149),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(147),
    [sym_unit_literal] = ACTIONS(147),
    [sym_number] = ACTIONS(149),
    [sym_wildcard] = ACTIONS(149),
    [anon_sym_POUND_LBRACK] = ACTIONS(147),
    [anon_sym_RBRACK] = ACTIONS(147),
    [anon_sym_LBRACE] = ACTIONS(147),
    [anon_sym_RBRACE] = ACTIONS(147),
    [anon_sym_LPAREN] = ACTIONS(147),
    [anon_sym_RPAREN] = ACTIONS(147),
    [anon_sym_LBRACK] = ACTIONS(147),
  },
  [21] = {
    [ts_builtin_sym_end] = ACTIONS(151),
    [sym_identifier] = ACTIONS(153),
    [anon_sym_COLON] = ACTIONS(153),
    [anon_sym_COMMA] = ACTIONS(151),
    [anon_sym_DOT] = ACTIONS(153),
    [anon_sym_COLON_COLON] = ACTIONS(151),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(151),
    [anon_sym_LT] = ACTIONS(151),
    [anon_sym_GT] = ACTIONS(151),
    [anon_sym_EQ] = ACTIONS(151),
    [anon_sym_SEMI] = ACTIONS(151),
    [anon_sym_device] = ACTIONS(153),
    [anon_sym_trait] = ACTIONS(153),
    [anon_sym_part] = ACTIONS(153),
    [anon_sym_fn] = ACTIONS(153),
    [anon_sym_design] = ACTIONS(153),
    [anon_sym_subdesign] = ACTIONS(153),
    [anon_sym_footprint] = ACTIONS(153),
    [anon_sym_pad] = ACTIONS(153),
    [anon_sym_use] = ACTIONS(153),
    [anon_sym_impl] = ACTIONS(153),
    [anon_sym_for] = ACTIONS(153),
    [anon_sym_inst] = ACTIONS(153),
    [anon_sym_net] = ACTIONS(153),
    [anon_sym_pub] = ACTIONS(153),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(151),
    [sym_unit_literal] = ACTIONS(151),
    [sym_number] = ACTIONS(153),
    [sym_wildcard] = ACTIONS(153),
    [anon_sym_POUND_LBRACK] = ACTIONS(151),
    [anon_sym_RBRACK] = ACTIONS(151),
    [anon_sym_LBRACE] = ACTIONS(151),
    [anon_sym_RBRACE] = ACTIONS(151),
    [anon_sym_LPAREN] = ACTIONS(151),
    [anon_sym_RPAREN] = ACTIONS(151),
    [anon_sym_LBRACK] = ACTIONS(151),
  },
  [22] = {
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_identifier] = ACTIONS(155),
    [anon_sym_COLON] = ACTIONS(116),
    [anon_sym_COMMA] = ACTIONS(112),
    [anon_sym_DOT] = ACTIONS(116),
    [anon_sym_COLON_COLON] = ACTIONS(112),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(112),
    [anon_sym_LT] = ACTIONS(112),
    [anon_sym_GT] = ACTIONS(112),
    [anon_sym_EQ] = ACTIONS(112),
    [anon_sym_SEMI] = ACTIONS(112),
    [anon_sym_device] = ACTIONS(116),
    [anon_sym_trait] = ACTIONS(116),
    [anon_sym_part] = ACTIONS(116),
    [anon_sym_fn] = ACTIONS(116),
    [anon_sym_design] = ACTIONS(116),
    [anon_sym_subdesign] = ACTIONS(116),
    [anon_sym_footprint] = ACTIONS(116),
    [anon_sym_pad] = ACTIONS(116),
    [anon_sym_use] = ACTIONS(116),
    [anon_sym_impl] = ACTIONS(116),
    [anon_sym_for] = ACTIONS(116),
    [anon_sym_inst] = ACTIONS(116),
    [anon_sym_net] = ACTIONS(116),
    [anon_sym_pub] = ACTIONS(116),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(112),
    [sym_unit_literal] = ACTIONS(112),
    [sym_number] = ACTIONS(116),
    [sym_wildcard] = ACTIONS(116),
    [anon_sym_POUND_LBRACK] = ACTIONS(112),
    [anon_sym_RBRACK] = ACTIONS(112),
    [anon_sym_LBRACE] = ACTIONS(112),
    [anon_sym_RBRACE] = ACTIONS(112),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(112),
    [anon_sym_LBRACK] = ACTIONS(112),
  },
  [23] = {
    [ts_builtin_sym_end] = ACTIONS(157),
    [sym_identifier] = ACTIONS(159),
    [anon_sym_COLON] = ACTIONS(159),
    [anon_sym_COMMA] = ACTIONS(157),
    [anon_sym_DOT] = ACTIONS(159),
    [anon_sym_COLON_COLON] = ACTIONS(157),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(157),
    [anon_sym_LT] = ACTIONS(157),
    [anon_sym_GT] = ACTIONS(157),
    [anon_sym_EQ] = ACTIONS(157),
    [anon_sym_SEMI] = ACTIONS(157),
    [anon_sym_device] = ACTIONS(159),
    [anon_sym_trait] = ACTIONS(159),
    [anon_sym_part] = ACTIONS(159),
    [anon_sym_fn] = ACTIONS(159),
    [anon_sym_design] = ACTIONS(159),
    [anon_sym_subdesign] = ACTIONS(159),
    [anon_sym_footprint] = ACTIONS(159),
    [anon_sym_pad] = ACTIONS(159),
    [anon_sym_use] = ACTIONS(159),
    [anon_sym_impl] = ACTIONS(159),
    [anon_sym_for] = ACTIONS(159),
    [anon_sym_inst] = ACTIONS(159),
    [anon_sym_net] = ACTIONS(159),
    [anon_sym_pub] = ACTIONS(159),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(157),
    [sym_unit_literal] = ACTIONS(157),
    [sym_number] = ACTIONS(159),
    [sym_wildcard] = ACTIONS(159),
    [anon_sym_POUND_LBRACK] = ACTIONS(157),
    [anon_sym_RBRACK] = ACTIONS(157),
    [anon_sym_LBRACE] = ACTIONS(157),
    [anon_sym_RBRACE] = ACTIONS(157),
    [anon_sym_LPAREN] = ACTIONS(157),
    [anon_sym_RPAREN] = ACTIONS(157),
    [anon_sym_LBRACK] = ACTIONS(157),
  },
  [24] = {
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_identifier] = ACTIONS(161),
    [anon_sym_COLON] = ACTIONS(116),
    [anon_sym_COMMA] = ACTIONS(112),
    [anon_sym_DOT] = ACTIONS(116),
    [anon_sym_COLON_COLON] = ACTIONS(112),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(112),
    [anon_sym_LT] = ACTIONS(112),
    [anon_sym_GT] = ACTIONS(112),
    [anon_sym_EQ] = ACTIONS(112),
    [anon_sym_SEMI] = ACTIONS(112),
    [anon_sym_device] = ACTIONS(116),
    [anon_sym_trait] = ACTIONS(116),
    [anon_sym_part] = ACTIONS(116),
    [anon_sym_fn] = ACTIONS(116),
    [anon_sym_design] = ACTIONS(116),
    [anon_sym_subdesign] = ACTIONS(116),
    [anon_sym_footprint] = ACTIONS(116),
    [anon_sym_pad] = ACTIONS(116),
    [anon_sym_use] = ACTIONS(116),
    [anon_sym_impl] = ACTIONS(116),
    [anon_sym_for] = ACTIONS(116),
    [anon_sym_inst] = ACTIONS(116),
    [anon_sym_net] = ACTIONS(116),
    [anon_sym_pub] = ACTIONS(116),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(112),
    [sym_unit_literal] = ACTIONS(112),
    [sym_number] = ACTIONS(163),
    [sym_wildcard] = ACTIONS(116),
    [anon_sym_POUND_LBRACK] = ACTIONS(112),
    [anon_sym_RBRACK] = ACTIONS(112),
    [anon_sym_LBRACE] = ACTIONS(112),
    [anon_sym_RBRACE] = ACTIONS(112),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(112),
    [anon_sym_LBRACK] = ACTIONS(112),
  },
  [25] = {
    [ts_builtin_sym_end] = ACTIONS(165),
    [sym_identifier] = ACTIONS(167),
    [anon_sym_COLON] = ACTIONS(167),
    [anon_sym_COMMA] = ACTIONS(165),
    [anon_sym_DOT] = ACTIONS(167),
    [anon_sym_COLON_COLON] = ACTIONS(165),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(165),
    [anon_sym_LT] = ACTIONS(165),
    [anon_sym_GT] = ACTIONS(165),
    [anon_sym_EQ] = ACTIONS(165),
    [anon_sym_SEMI] = ACTIONS(165),
    [anon_sym_device] = ACTIONS(167),
    [anon_sym_trait] = ACTIONS(167),
    [anon_sym_part] = ACTIONS(167),
    [anon_sym_fn] = ACTIONS(167),
    [anon_sym_design] = ACTIONS(167),
    [anon_sym_subdesign] = ACTIONS(167),
    [anon_sym_footprint] = ACTIONS(167),
    [anon_sym_pad] = ACTIONS(167),
    [anon_sym_use] = ACTIONS(167),
    [anon_sym_impl] = ACTIONS(167),
    [anon_sym_for] = ACTIONS(167),
    [anon_sym_inst] = ACTIONS(167),
    [anon_sym_net] = ACTIONS(167),
    [anon_sym_pub] = ACTIONS(167),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(165),
    [sym_unit_literal] = ACTIONS(165),
    [sym_number] = ACTIONS(167),
    [sym_wildcard] = ACTIONS(167),
    [anon_sym_POUND_LBRACK] = ACTIONS(165),
    [anon_sym_RBRACK] = ACTIONS(165),
    [anon_sym_LBRACE] = ACTIONS(165),
    [anon_sym_RBRACE] = ACTIONS(165),
    [anon_sym_LPAREN] = ACTIONS(165),
    [anon_sym_RPAREN] = ACTIONS(165),
    [anon_sym_LBRACK] = ACTIONS(165),
  },
  [26] = {
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_identifier] = ACTIONS(169),
    [anon_sym_COLON] = ACTIONS(116),
    [anon_sym_COMMA] = ACTIONS(112),
    [anon_sym_DOT] = ACTIONS(116),
    [anon_sym_COLON_COLON] = ACTIONS(112),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(112),
    [anon_sym_LT] = ACTIONS(112),
    [anon_sym_GT] = ACTIONS(112),
    [anon_sym_EQ] = ACTIONS(112),
    [anon_sym_SEMI] = ACTIONS(112),
    [anon_sym_device] = ACTIONS(116),
    [anon_sym_trait] = ACTIONS(116),
    [anon_sym_part] = ACTIONS(116),
    [anon_sym_fn] = ACTIONS(116),
    [anon_sym_design] = ACTIONS(116),
    [anon_sym_subdesign] = ACTIONS(116),
    [anon_sym_footprint] = ACTIONS(116),
    [anon_sym_pad] = ACTIONS(116),
    [anon_sym_use] = ACTIONS(116),
    [anon_sym_impl] = ACTIONS(116),
    [anon_sym_for] = ACTIONS(116),
    [anon_sym_inst] = ACTIONS(116),
    [anon_sym_net] = ACTIONS(116),
    [anon_sym_pub] = ACTIONS(116),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(112),
    [sym_unit_literal] = ACTIONS(112),
    [sym_number] = ACTIONS(116),
    [sym_wildcard] = ACTIONS(169),
    [anon_sym_POUND_LBRACK] = ACTIONS(112),
    [anon_sym_RBRACK] = ACTIONS(112),
    [anon_sym_LBRACE] = ACTIONS(112),
    [anon_sym_RBRACE] = ACTIONS(112),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(112),
    [anon_sym_LBRACK] = ACTIONS(112),
  },
  [27] = {
    [ts_builtin_sym_end] = ACTIONS(171),
    [sym_identifier] = ACTIONS(173),
    [anon_sym_COLON] = ACTIONS(173),
    [anon_sym_COMMA] = ACTIONS(171),
    [anon_sym_DOT] = ACTIONS(173),
    [anon_sym_COLON_COLON] = ACTIONS(171),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(171),
    [anon_sym_LT] = ACTIONS(171),
    [anon_sym_GT] = ACTIONS(171),
    [anon_sym_EQ] = ACTIONS(171),
    [anon_sym_SEMI] = ACTIONS(171),
    [anon_sym_device] = ACTIONS(173),
    [anon_sym_trait] = ACTIONS(173),
    [anon_sym_part] = ACTIONS(173),
    [anon_sym_fn] = ACTIONS(173),
    [anon_sym_design] = ACTIONS(173),
    [anon_sym_subdesign] = ACTIONS(173),
    [anon_sym_footprint] = ACTIONS(173),
    [anon_sym_pad] = ACTIONS(173),
    [anon_sym_use] = ACTIONS(173),
    [anon_sym_impl] = ACTIONS(173),
    [anon_sym_for] = ACTIONS(173),
    [anon_sym_inst] = ACTIONS(173),
    [anon_sym_net] = ACTIONS(173),
    [anon_sym_pub] = ACTIONS(173),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(171),
    [sym_unit_literal] = ACTIONS(171),
    [sym_number] = ACTIONS(173),
    [sym_wildcard] = ACTIONS(173),
    [anon_sym_POUND_LBRACK] = ACTIONS(171),
    [anon_sym_RBRACK] = ACTIONS(171),
    [anon_sym_LBRACE] = ACTIONS(171),
    [anon_sym_RBRACE] = ACTIONS(171),
    [anon_sym_LPAREN] = ACTIONS(171),
    [anon_sym_RPAREN] = ACTIONS(171),
    [anon_sym_LBRACK] = ACTIONS(171),
  },
  [28] = {
    [ts_builtin_sym_end] = ACTIONS(175),
    [sym_identifier] = ACTIONS(177),
    [anon_sym_COLON] = ACTIONS(177),
    [anon_sym_COMMA] = ACTIONS(175),
    [anon_sym_DOT] = ACTIONS(177),
    [anon_sym_COLON_COLON] = ACTIONS(175),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(175),
    [anon_sym_LT] = ACTIONS(175),
    [anon_sym_GT] = ACTIONS(175),
    [anon_sym_EQ] = ACTIONS(175),
    [anon_sym_SEMI] = ACTIONS(175),
    [anon_sym_device] = ACTIONS(177),
    [anon_sym_trait] = ACTIONS(177),
    [anon_sym_part] = ACTIONS(177),
    [anon_sym_fn] = ACTIONS(177),
    [anon_sym_design] = ACTIONS(177),
    [anon_sym_subdesign] = ACTIONS(177),
    [anon_sym_footprint] = ACTIONS(177),
    [anon_sym_pad] = ACTIONS(177),
    [anon_sym_use] = ACTIONS(177),
    [anon_sym_impl] = ACTIONS(177),
    [anon_sym_for] = ACTIONS(177),
    [anon_sym_inst] = ACTIONS(177),
    [anon_sym_net] = ACTIONS(177),
    [anon_sym_pub] = ACTIONS(177),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(175),
    [sym_unit_literal] = ACTIONS(175),
    [sym_number] = ACTIONS(177),
    [sym_wildcard] = ACTIONS(177),
    [anon_sym_POUND_LBRACK] = ACTIONS(175),
    [anon_sym_RBRACK] = ACTIONS(175),
    [anon_sym_LBRACE] = ACTIONS(175),
    [anon_sym_RBRACE] = ACTIONS(175),
    [anon_sym_LPAREN] = ACTIONS(175),
    [anon_sym_RPAREN] = ACTIONS(175),
    [anon_sym_LBRACK] = ACTIONS(175),
  },
  [29] = {
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_identifier] = ACTIONS(116),
    [anon_sym_COLON] = ACTIONS(116),
    [anon_sym_COMMA] = ACTIONS(112),
    [anon_sym_DOT] = ACTIONS(116),
    [anon_sym_COLON_COLON] = ACTIONS(112),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(112),
    [anon_sym_LT] = ACTIONS(112),
    [anon_sym_GT] = ACTIONS(112),
    [anon_sym_EQ] = ACTIONS(112),
    [anon_sym_SEMI] = ACTIONS(112),
    [anon_sym_device] = ACTIONS(179),
    [anon_sym_trait] = ACTIONS(179),
    [anon_sym_part] = ACTIONS(179),
    [anon_sym_fn] = ACTIONS(179),
    [anon_sym_design] = ACTIONS(179),
    [anon_sym_subdesign] = ACTIONS(179),
    [anon_sym_footprint] = ACTIONS(179),
    [anon_sym_pad] = ACTIONS(179),
    [anon_sym_use] = ACTIONS(116),
    [anon_sym_impl] = ACTIONS(116),
    [anon_sym_for] = ACTIONS(116),
    [anon_sym_inst] = ACTIONS(116),
    [anon_sym_net] = ACTIONS(116),
    [anon_sym_pub] = ACTIONS(116),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(112),
    [sym_unit_literal] = ACTIONS(112),
    [sym_number] = ACTIONS(116),
    [sym_wildcard] = ACTIONS(116),
    [anon_sym_POUND_LBRACK] = ACTIONS(112),
    [anon_sym_RBRACK] = ACTIONS(112),
    [anon_sym_LBRACE] = ACTIONS(112),
    [anon_sym_RBRACE] = ACTIONS(112),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(112),
    [anon_sym_LBRACK] = ACTIONS(112),
  },
  [30] = {
    [ts_builtin_sym_end] = ACTIONS(181),
    [sym_identifier] = ACTIONS(183),
    [anon_sym_COLON] = ACTIONS(183),
    [anon_sym_COMMA] = ACTIONS(181),
    [anon_sym_DOT] = ACTIONS(183),
    [anon_sym_COLON_COLON] = ACTIONS(181),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(181),
    [anon_sym_LT] = ACTIONS(181),
    [anon_sym_GT] = ACTIONS(181),
    [anon_sym_EQ] = ACTIONS(181),
    [anon_sym_SEMI] = ACTIONS(181),
    [anon_sym_device] = ACTIONS(183),
    [anon_sym_trait] = ACTIONS(183),
    [anon_sym_part] = ACTIONS(183),
    [anon_sym_fn] = ACTIONS(183),
    [anon_sym_design] = ACTIONS(183),
    [anon_sym_subdesign] = ACTIONS(183),
    [anon_sym_footprint] = ACTIONS(183),
    [anon_sym_pad] = ACTIONS(183),
    [anon_sym_use] = ACTIONS(183),
    [anon_sym_impl] = ACTIONS(183),
    [anon_sym_for] = ACTIONS(183),
    [anon_sym_inst] = ACTIONS(183),
    [anon_sym_net] = ACTIONS(183),
    [anon_sym_pub] = ACTIONS(183),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(181),
    [sym_unit_literal] = ACTIONS(181),
    [sym_number] = ACTIONS(183),
    [sym_wildcard] = ACTIONS(183),
    [anon_sym_POUND_LBRACK] = ACTIONS(181),
    [anon_sym_RBRACK] = ACTIONS(181),
    [anon_sym_LBRACE] = ACTIONS(181),
    [anon_sym_RBRACE] = ACTIONS(181),
    [anon_sym_LPAREN] = ACTIONS(181),
    [anon_sym_RPAREN] = ACTIONS(181),
    [anon_sym_LBRACK] = ACTIONS(181),
  },
  [31] = {
    [ts_builtin_sym_end] = ACTIONS(185),
    [sym_identifier] = ACTIONS(187),
    [anon_sym_COLON] = ACTIONS(187),
    [anon_sym_COMMA] = ACTIONS(185),
    [anon_sym_DOT] = ACTIONS(187),
    [anon_sym_COLON_COLON] = ACTIONS(185),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(185),
    [anon_sym_LT] = ACTIONS(185),
    [anon_sym_GT] = ACTIONS(185),
    [anon_sym_EQ] = ACTIONS(185),
    [anon_sym_SEMI] = ACTIONS(185),
    [anon_sym_device] = ACTIONS(187),
    [anon_sym_trait] = ACTIONS(187),
    [anon_sym_part] = ACTIONS(187),
    [anon_sym_fn] = ACTIONS(187),
    [anon_sym_design] = ACTIONS(187),
    [anon_sym_subdesign] = ACTIONS(187),
    [anon_sym_footprint] = ACTIONS(187),
    [anon_sym_pad] = ACTIONS(187),
    [anon_sym_use] = ACTIONS(187),
    [anon_sym_impl] = ACTIONS(187),
    [anon_sym_for] = ACTIONS(187),
    [anon_sym_inst] = ACTIONS(187),
    [anon_sym_net] = ACTIONS(187),
    [anon_sym_pub] = ACTIONS(187),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(185),
    [sym_unit_literal] = ACTIONS(185),
    [sym_number] = ACTIONS(187),
    [sym_wildcard] = ACTIONS(187),
    [anon_sym_POUND_LBRACK] = ACTIONS(185),
    [anon_sym_RBRACK] = ACTIONS(185),
    [anon_sym_LBRACE] = ACTIONS(185),
    [anon_sym_RBRACE] = ACTIONS(185),
    [anon_sym_LPAREN] = ACTIONS(185),
    [anon_sym_RPAREN] = ACTIONS(185),
    [anon_sym_LBRACK] = ACTIONS(185),
  },
  [32] = {
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_identifier] = ACTIONS(161),
    [anon_sym_COLON] = ACTIONS(116),
    [anon_sym_COMMA] = ACTIONS(112),
    [anon_sym_DOT] = ACTIONS(116),
    [anon_sym_COLON_COLON] = ACTIONS(112),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(112),
    [anon_sym_LT] = ACTIONS(112),
    [anon_sym_GT] = ACTIONS(112),
    [anon_sym_EQ] = ACTIONS(112),
    [anon_sym_SEMI] = ACTIONS(112),
    [anon_sym_device] = ACTIONS(116),
    [anon_sym_trait] = ACTIONS(116),
    [anon_sym_part] = ACTIONS(116),
    [anon_sym_fn] = ACTIONS(116),
    [anon_sym_design] = ACTIONS(116),
    [anon_sym_subdesign] = ACTIONS(116),
    [anon_sym_footprint] = ACTIONS(116),
    [anon_sym_pad] = ACTIONS(116),
    [anon_sym_use] = ACTIONS(116),
    [anon_sym_impl] = ACTIONS(116),
    [anon_sym_for] = ACTIONS(116),
    [anon_sym_inst] = ACTIONS(116),
    [anon_sym_net] = ACTIONS(116),
    [anon_sym_pub] = ACTIONS(116),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(112),
    [sym_unit_literal] = ACTIONS(112),
    [sym_number] = ACTIONS(116),
    [sym_wildcard] = ACTIONS(116),
    [anon_sym_POUND_LBRACK] = ACTIONS(112),
    [anon_sym_RBRACK] = ACTIONS(112),
    [anon_sym_LBRACE] = ACTIONS(112),
    [anon_sym_RBRACE] = ACTIONS(112),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(112),
    [anon_sym_LBRACK] = ACTIONS(112),
  },
  [33] = {
    [ts_builtin_sym_end] = ACTIONS(189),
    [sym_identifier] = ACTIONS(191),
    [anon_sym_COLON] = ACTIONS(191),
    [anon_sym_COMMA] = ACTIONS(189),
    [anon_sym_DOT] = ACTIONS(191),
    [anon_sym_COLON_COLON] = ACTIONS(189),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(189),
    [anon_sym_LT] = ACTIONS(189),
    [anon_sym_GT] = ACTIONS(189),
    [anon_sym_EQ] = ACTIONS(189),
    [anon_sym_SEMI] = ACTIONS(189),
    [anon_sym_device] = ACTIONS(191),
    [anon_sym_trait] = ACTIONS(191),
    [anon_sym_part] = ACTIONS(191),
    [anon_sym_fn] = ACTIONS(191),
    [anon_sym_design] = ACTIONS(191),
    [anon_sym_subdesign] = ACTIONS(191),
    [anon_sym_footprint] = ACTIONS(191),
    [anon_sym_pad] = ACTIONS(191),
    [anon_sym_use] = ACTIONS(191),
    [anon_sym_impl] = ACTIONS(191),
    [anon_sym_for] = ACTIONS(191),
    [anon_sym_inst] = ACTIONS(191),
    [anon_sym_net] = ACTIONS(191),
    [anon_sym_pub] = ACTIONS(191),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(189),
    [sym_unit_literal] = ACTIONS(189),
    [sym_number] = ACTIONS(191),
    [sym_wildcard] = ACTIONS(191),
    [anon_sym_POUND_LBRACK] = ACTIONS(189),
    [anon_sym_RBRACK] = ACTIONS(189),
    [anon_sym_LBRACE] = ACTIONS(189),
    [anon_sym_RBRACE] = ACTIONS(189),
    [anon_sym_LPAREN] = ACTIONS(189),
    [anon_sym_RPAREN] = ACTIONS(189),
    [anon_sym_LBRACK] = ACTIONS(189),
  },
  [34] = {
    [ts_builtin_sym_end] = ACTIONS(193),
    [sym_identifier] = ACTIONS(195),
    [anon_sym_COLON] = ACTIONS(195),
    [anon_sym_COMMA] = ACTIONS(193),
    [anon_sym_DOT] = ACTIONS(195),
    [anon_sym_COLON_COLON] = ACTIONS(193),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(193),
    [anon_sym_LT] = ACTIONS(193),
    [anon_sym_GT] = ACTIONS(193),
    [anon_sym_EQ] = ACTIONS(193),
    [anon_sym_SEMI] = ACTIONS(193),
    [anon_sym_device] = ACTIONS(195),
    [anon_sym_trait] = ACTIONS(195),
    [anon_sym_part] = ACTIONS(195),
    [anon_sym_fn] = ACTIONS(195),
    [anon_sym_design] = ACTIONS(195),
    [anon_sym_subdesign] = ACTIONS(195),
    [anon_sym_footprint] = ACTIONS(195),
    [anon_sym_pad] = ACTIONS(195),
    [anon_sym_use] = ACTIONS(195),
    [anon_sym_impl] = ACTIONS(195),
    [anon_sym_for] = ACTIONS(195),
    [anon_sym_inst] = ACTIONS(195),
    [anon_sym_net] = ACTIONS(195),
    [anon_sym_pub] = ACTIONS(195),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(193),
    [sym_unit_literal] = ACTIONS(193),
    [sym_number] = ACTIONS(195),
    [sym_wildcard] = ACTIONS(195),
    [anon_sym_POUND_LBRACK] = ACTIONS(193),
    [anon_sym_RBRACK] = ACTIONS(193),
    [anon_sym_LBRACE] = ACTIONS(193),
    [anon_sym_RBRACE] = ACTIONS(193),
    [anon_sym_LPAREN] = ACTIONS(193),
    [anon_sym_RPAREN] = ACTIONS(193),
    [anon_sym_LBRACK] = ACTIONS(193),
  },
  [35] = {
    [ts_builtin_sym_end] = ACTIONS(197),
    [sym_identifier] = ACTIONS(199),
    [anon_sym_COLON] = ACTIONS(199),
    [anon_sym_COMMA] = ACTIONS(197),
    [anon_sym_DOT] = ACTIONS(199),
    [anon_sym_COLON_COLON] = ACTIONS(197),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(197),
    [anon_sym_LT] = ACTIONS(197),
    [anon_sym_GT] = ACTIONS(197),
    [anon_sym_EQ] = ACTIONS(197),
    [anon_sym_SEMI] = ACTIONS(197),
    [anon_sym_device] = ACTIONS(199),
    [anon_sym_trait] = ACTIONS(199),
    [anon_sym_part] = ACTIONS(199),
    [anon_sym_fn] = ACTIONS(199),
    [anon_sym_design] = ACTIONS(199),
    [anon_sym_subdesign] = ACTIONS(199),
    [anon_sym_footprint] = ACTIONS(199),
    [anon_sym_pad] = ACTIONS(199),
    [anon_sym_use] = ACTIONS(199),
    [anon_sym_impl] = ACTIONS(199),
    [anon_sym_for] = ACTIONS(199),
    [anon_sym_inst] = ACTIONS(199),
    [anon_sym_net] = ACTIONS(199),
    [anon_sym_pub] = ACTIONS(199),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(197),
    [sym_unit_literal] = ACTIONS(197),
    [sym_number] = ACTIONS(199),
    [sym_wildcard] = ACTIONS(199),
    [anon_sym_POUND_LBRACK] = ACTIONS(197),
    [anon_sym_RBRACK] = ACTIONS(197),
    [anon_sym_LBRACE] = ACTIONS(197),
    [anon_sym_RBRACE] = ACTIONS(197),
    [anon_sym_LPAREN] = ACTIONS(197),
    [anon_sym_RPAREN] = ACTIONS(197),
    [anon_sym_LBRACK] = ACTIONS(197),
  },
  [36] = {
    [ts_builtin_sym_end] = ACTIONS(201),
    [sym_identifier] = ACTIONS(203),
    [anon_sym_COLON] = ACTIONS(203),
    [anon_sym_COMMA] = ACTIONS(201),
    [anon_sym_DOT] = ACTIONS(203),
    [anon_sym_COLON_COLON] = ACTIONS(201),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(201),
    [anon_sym_LT] = ACTIONS(201),
    [anon_sym_GT] = ACTIONS(201),
    [anon_sym_EQ] = ACTIONS(201),
    [anon_sym_SEMI] = ACTIONS(201),
    [anon_sym_device] = ACTIONS(203),
    [anon_sym_trait] = ACTIONS(203),
    [anon_sym_part] = ACTIONS(203),
    [anon_sym_fn] = ACTIONS(203),
    [anon_sym_design] = ACTIONS(203),
    [anon_sym_subdesign] = ACTIONS(203),
    [anon_sym_footprint] = ACTIONS(203),
    [anon_sym_pad] = ACTIONS(203),
    [anon_sym_use] = ACTIONS(203),
    [anon_sym_impl] = ACTIONS(203),
    [anon_sym_for] = ACTIONS(203),
    [anon_sym_inst] = ACTIONS(203),
    [anon_sym_net] = ACTIONS(203),
    [anon_sym_pub] = ACTIONS(203),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(201),
    [sym_unit_literal] = ACTIONS(201),
    [sym_number] = ACTIONS(203),
    [sym_wildcard] = ACTIONS(203),
    [anon_sym_POUND_LBRACK] = ACTIONS(201),
    [anon_sym_RBRACK] = ACTIONS(201),
    [anon_sym_LBRACE] = ACTIONS(201),
    [anon_sym_RBRACE] = ACTIONS(201),
    [anon_sym_LPAREN] = ACTIONS(201),
    [anon_sym_RPAREN] = ACTIONS(201),
    [anon_sym_LBRACK] = ACTIONS(201),
  },
  [37] = {
    [ts_builtin_sym_end] = ACTIONS(128),
    [sym_identifier] = ACTIONS(130),
    [anon_sym_COLON] = ACTIONS(130),
    [anon_sym_COMMA] = ACTIONS(128),
    [anon_sym_DOT] = ACTIONS(130),
    [anon_sym_COLON_COLON] = ACTIONS(128),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(128),
    [anon_sym_LT] = ACTIONS(128),
    [anon_sym_GT] = ACTIONS(128),
    [anon_sym_EQ] = ACTIONS(128),
    [anon_sym_SEMI] = ACTIONS(128),
    [anon_sym_device] = ACTIONS(130),
    [anon_sym_trait] = ACTIONS(130),
    [anon_sym_part] = ACTIONS(130),
    [anon_sym_fn] = ACTIONS(130),
    [anon_sym_design] = ACTIONS(130),
    [anon_sym_subdesign] = ACTIONS(130),
    [anon_sym_footprint] = ACTIONS(130),
    [anon_sym_pad] = ACTIONS(130),
    [anon_sym_use] = ACTIONS(130),
    [anon_sym_impl] = ACTIONS(130),
    [anon_sym_for] = ACTIONS(130),
    [anon_sym_inst] = ACTIONS(130),
    [anon_sym_net] = ACTIONS(130),
    [anon_sym_pub] = ACTIONS(130),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(128),
    [sym_unit_literal] = ACTIONS(128),
    [sym_number] = ACTIONS(130),
    [sym_wildcard] = ACTIONS(130),
    [anon_sym_POUND_LBRACK] = ACTIONS(128),
    [anon_sym_RBRACK] = ACTIONS(128),
    [anon_sym_LBRACE] = ACTIONS(128),
    [anon_sym_RBRACE] = ACTIONS(128),
    [anon_sym_LPAREN] = ACTIONS(128),
    [anon_sym_RPAREN] = ACTIONS(128),
    [anon_sym_LBRACK] = ACTIONS(128),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_identifier,
    STATE(28), 1,
      sym_path,
  [10] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_for,
  [17] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_identifier,
  [24] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym_identifier,
  [31] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(38)] = 0,
  [SMALL_STATE(39)] = 10,
  [SMALL_STATE(40)] = 17,
  [SMALL_STATE(41)] = 24,
  [SMALL_STATE(42)] = 31,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__keyword_fallback, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__keyword_fallback, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 5),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 3, 0, 5),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_declaration, 2, 0, 3),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_declaration, 2, 0, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inst_statement, 2, 0, 4),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inst_statement, 2, 0, 4),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_net_statement, 2, 0, 4),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_net_statement, 2, 0, 4),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parens, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parens, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brackets, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brackets, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_impl_declaration, 4, 0, 6),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_impl_declaration, 4, 0, 6),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brackets, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brackets, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 1),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 2, 0, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pad_placement, 2, 0, 2),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pad_placement, 2, 0, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parens, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parens, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cohdl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
