#!/usr/bin/env python3
"""Generate the `passive` library (lib/passive/) — chip resistors and MLCCs.

The catalog is DATA, not hand-authored source: thousands of parts whose only
per-part variation is (size, value, tolerance, dielectric, voltage) and the
manufacturer part numbers those fields encode. Generating it keeps every part
consistent with the same rules, and keeps a value-grid change a one-line edit
here instead of a thousand-line hand edit there.

Run from the repository root:

    python3 tools/gen_passive.py && cargo run -- fmt lib/passive --check

The output is already in `cohdl fmt` canonical form — the `--check` above is
the gate that keeps it that way (a generator that needed `fmt` to fix it up
would make regeneration produce a diff against the committed bytes).

Land patterns come from KiCad's own footprint library (the same provenance
std's chip lands had), resistor land per RFC-021: resistors and capacitors
share one nominal CHIP-<EIA> land, and the resistor's is the more generous.
"""

import pathlib
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "lib" / "passive" / "src"

# --------------------------------------------------------------------------
# Land patterns — KiCad Resistor_SMD.pretty/R_<EIA>_<metric>Metric.kicad_mod
# (pad size, pad x offset, courtyard extent), transcribed verbatim.
# --------------------------------------------------------------------------

LANDS = {
    "01005": {"metric": "0402", "pad": (0.4, 0.3), "x": 0.25, "cy": (1.2, 0.6)},
    "0201": {"metric": "0603", "pad": (0.46, 0.4), "x": 0.32, "cy": (1.4, 0.7)},
    "0402": {"metric": "1005", "pad": (0.54, 0.64), "x": 0.51, "cy": (1.86, 0.94)},
    "0603": {"metric": "1608", "pad": (0.8, 0.95), "x": 0.825, "cy": (2.96, 1.46)},
    "0805": {"metric": "2012", "pad": (1.025, 1.4), "x": 0.9125, "cy": (3.36, 1.9)},
    "1206": {"metric": "3216", "pad": (1.125, 1.75), "x": 1.4625, "cy": (4.56, 2.26)},
    "1210": {"metric": "3225", "pad": (1.125, 2.65), "x": 1.4625, "cy": (4.56, 3.16)},
    "2010": {"metric": "5025", "pad": (1.225, 2.65), "x": 2.3125, "cy": (6.36, 3.16)},
    "2512": {"metric": "6332", "pad": (1.225, 3.35), "x": 2.9625, "cy": (7.66, 3.86)},
}

# The reference designator sits above the courtyard, same offset std used.
SILK_GAP = 0.7


def mm(v):
    """A Length literal in canonical form: no trailing zeros, always `mm`."""
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return f"{s or '0'}mm"


def header(title, note=""):
    out = [f"// {title}"]
    if note:
        out += ["//"] + [f"// {line}".rstrip() for line in note.strip().split("\n")]
    return "\n".join(out) + "\n"


GENERATED = (
    "GENERATED by tools/gen_passive.py — do not hand-edit.\n"
    "Regenerate after changing the value grid or a vendor's part-number rule."
)


def emit_pads():
    body = [
        header(
            "Chip-passive pads, one per EIA case size.",
            GENERATED
            + "\n\n"
            + "Geometry: KiCad Resistor_SMD.pretty/R_<EIA>_<metric>Metric.kicad_mod.\n"
            + "Per RFC-021 one CHIP land serves resistors and capacitors alike, and\n"
            + "the resistor land is the more generous of the two.",
        )
    ]
    for eia, land in LANDS.items():
        w, h = land["pad"]
        body.append(
            f"// KiCad R_{eia}_{land['metric']}Metric pad ({mm(w)} x {mm(h)}).\n"
            f"pub pad P_Chip_{eia} {{\n"
            f"    shape: rect\n"
            f"    size: ({mm(w)}, {mm(h)})\n"
            f"    layer: top_copper\n"
            f"    plating: smd\n"
            f"}}\n"
        )
    return "\n".join(body)


def emit_footprints():
    body = [
        header(
            "Chip-passive lands, one per EIA case size (RFC-021 `CHIP_<EIA>`).",
            GENERATED
            + "\n\n"
            + "The footprint's own identifier IS its IPC-7351 name, so a size appears\n"
            + "exactly once in this library: as `CHIP_<EIA>` here, and as the matching\n"
            + "`R<EIA>`/`C<EIA>` device variant.",
        )
    ]
    for eia, land in LANDS.items():
        cw, ch = land["cy"]
        body.append(
            f"pub footprint CHIP_{eia} {{\n"
            f"    pad 1: P_Chip_{eia} at ({mm(-land['x'])}, 0mm)\n"
            f"    pad 2: P_Chip_{eia} at ({mm(land['x'])}, 0mm)\n"
            f"    courtyard {{ shape: rect, at: (0mm, 0mm), size: ({mm(cw)}, {mm(ch)}) }}\n"
            f"    silkscreen_ref {{ at: (0mm, {mm(-(ch / 2 + SILK_GAP))}) }}\n"
            f"}}\n"
        )
    return "\n".join(body)


# --------------------------------------------------------------------------
# Second sources for MLCCs.
#
# Samsung CL and Murata GRM part numbers carry a per-part thickness/electrode
# field that (size, dielectric, voltage, capacitance) does not determine — so
# unlike Yageo's and Vishay's, theirs cannot be derived, and CoHDL requires a
# real `mpn` on every `alt` (E802). Only individually verified numbers appear
# here; a part missing from this table ships with its Yageo primary alone
# rather than with an invented alternate.
# --------------------------------------------------------------------------

def load_verified():
    """MPN -> whether Yageo publishes a specsheet for it.

    Written by tools/verify_passive_mpns.py. Absent file = nothing known yet,
    in which case the datasheet tables alone decide (the pre-verification
    state). A recorded `false` always wins: it means the endpoint that serves
    every real Yageo part has never heard of this one.
    """
    import json

    path = pathlib.Path(__file__).resolve().parent / "passive_data" / "yageo_verified.json"
    if not path.is_file():
        return {}
    return json.loads(path.read_text())["verdicts"]


def load_samsung():
    """(size, volts, dielectric, farads) -> a real Samsung CL part number."""
    import json

    path = pathlib.Path(__file__).resolve().parent / "passive_data" / "samsung_cl.json"
    return json.loads(path.read_text())["parts"]


VERIFIED_ALTERNATES = {
    "C_100n_16V_X7R_0402": [
        ("Samsung", "CL05B104KO5NNNC"),
        ("Murata", "GRM155R71C104KA88D"),
    ],
    "C_1u_10V_X5R_0402": [
        ("Murata", "GRM155R61A105KE15D"),
        ("Samsung", "CL05A105KP5NNNC"),
    ],
    "C_10u_10V_X5R_0603": [
        ("Samsung", "CL10A106KP8NNNC"),
        ("Murata", "GRM188R61A106KE69D"),
    ],
    "C_4u7_10V_X5R_0603": [("Samsung", "CL10A475KP8NNNC")],
    "C_15p_50V_C0G_0402": [("Murata", "GRM1555C1H150JA01D")],
}

# --------------------------------------------------------------------------
# Devices
# --------------------------------------------------------------------------


def pin_block(variant):
    return (
        f"    pins[{variant}] {{\n"
        f"        required A: 1 [passive]\n"
        f"        required B: 2 [passive]\n"
        f"    }}\n"
    )


def emit_devices(cap_sizes):
    r_variants = [f"R{s}" for s in R_POWER]
    c_variants = [f"C{s}" for s in cap_sizes]
    out = [
        header(
            "The two chip-passive devices, one variant per case size (RFC-008).",
            GENERATED
            + "\n\n"
            + "A variant is not decoration: it carries the size's own rated power, so\n"
            + "`ChipResistor<10kohm, 1%>[R0402]` states 1/16 W and `[R1206]` states\n"
            + "1/4 W from the same declaration. Traits come from std — this library\n"
            + "adds devices and parts, not a second set of trait definitions.",
        ),
        f"pub device ChipResistor<R: Resistance, T: Tolerance = 1%> {{\n"
        f"    variants {{ {', '.join(r_variants)} }}\n\n"
        + "\n".join(pin_block(v) for v in r_variants)
        + "\n    spec {\n        resistance: R\n        tolerance: T\n    }\n"
        + "".join(
            f"    spec[R{size}] {{\n        power_rating: {power}\n    }}\n"
            for size, power in R_POWER.items()
        )
        + "}\n",
        "impl TwoTerminal for ChipResistor {}\n\nimpl Resistor for ChipResistor {}\n",
        f"pub device MLCC<C: Capacitance, V: Voltage = 16V, T: Tolerance = 10%> {{\n"
        f"    variants {{ {', '.join(c_variants)} }}\n\n"
        + "\n".join(pin_block(v) for v in c_variants)
        + "\n    spec {\n        capacitance: C\n        voltage_rating: V\n        tolerance: T\n    }\n"
        + "}\n",
        "impl TwoTerminal for MLCC {}\n\nimpl Capacitor for MLCC {}\n",
    ]
    return "\n".join(out)


# --------------------------------------------------------------------------
# Value series (IEC 60063) and the BS 1852 value tokens the part names use
# --------------------------------------------------------------------------

E24 = [
    100, 110, 120, 130, 150, 160, 180, 200, 220, 240, 270, 300,
    330, 360, 390, 430, 470, 510, 560, 620, 680, 750, 820, 910,
]  # fmt: skip

E96 = [
    100, 102, 105, 107, 110, 113, 115, 118, 121, 124, 127, 130,
    133, 137, 140, 143, 147, 150, 154, 158, 162, 165, 169, 174,
    178, 182, 187, 191, 196, 200, 205, 210, 215, 221, 226, 232,
    237, 243, 249, 255, 261, 267, 274, 280, 287, 294, 301, 309,
    316, 324, 332, 340, 348, 357, 365, 374, 383, 392, 402, 412,
    422, 432, 442, 453, 464, 475, 487, 499, 511, 523, 536, 549,
    562, 576, 590, 604, 619, 634, 649, 665, 681, 698, 715, 732,
    750, 768, 787, 806, 825, 845, 866, 887, 909, 931, 953, 976,
]  # fmt: skip

E12 = [100, 120, 150, 180, 220, 270, 330, 390, 470, 560, 680, 820]
E6 = [100, 150, 220, 330, 470, 680]
E3 = [100, 220, 470]


def digits(mantissa):
    """`100` -> "1", `499` -> "4.99", `470` -> "4.7" — significant digits only."""
    s = f"{mantissa / 100:.2f}".rstrip("0").rstrip(".")
    return s


def ohm_token(mantissa, decade):
    """BS 1852: the multiplier letter replaces the decimal point. 4.7k -> 4K7."""
    for exp, letter in ((6, "M"), (3, "K"), (0, "R")):
        if decade >= exp:
            scaled = digits(mantissa)
            shift = decade - exp
            whole, _, frac = scaled.partition(".")
            body = (whole + frac).ljust(len(whole) + shift, "0")
            head, tail = body[: len(whole) + shift], body[len(whole) + shift :]
            return f"{head}{letter}{tail}" if tail else f"{head}{letter}"
    raise ValueError(decade)


def ohm_literal(mantissa, decade):
    """A CoHDL Resistance literal: `4.7kohm`, `100ohm`, `1Mohm`."""
    for exp, suffix in ((6, "Mohm"), (3, "kohm"), (0, "ohm")):
        if decade >= exp:
            value = mantissa / 100 * (10 ** (decade - exp))
            s = f"{value:.6f}".rstrip("0").rstrip(".")
            return f"{s}{suffix}"
    raise ValueError(decade)


# --------------------------------------------------------------------------
# Resistors — Yageo RC_L series (primary), Vishay CRCW e3 (alternate)
#
# Yageo global part number, per the RC_L datasheet (PYU-RC_GROUP_51_ROHS_L,
# Nov 2025 V.14):  RC <size> <tolerance> <packing> <TCR> <reel> <value> L
#   tolerance  F = +/-1%, J = +/-5%      packing  R = paper taping reel
#   TCR        "-" = per spec            reel     07 = 7 inch, standard power
#   value      2-4 digits, R/K/M is the decimal point (the datasheet's own
#              examples: 97R6 = 97.6 ohm, 9K76 = 9760 ohm, 1M = 1 Mohm)
# so 10 kohm +/-1% in 0402 is RC0402FR-0710KL, and the datasheet's ordering
# example — RC0402JR-07100KL, 100 kohm +/-5% — falls out of the same rule.
#
# Vishay CRCW e3 takes a fixed-width 4-character code (3 significant digits,
# R/K/M the decimal point) and a tolerance-dependent tail: F -> FKED,
# J -> JNED (CRCW040210K0FKED / CRCW040210K0JNED).
# --------------------------------------------------------------------------

# Rated power per size, from the RC_L datasheet's characteristics tables.
R_POWER = {
    "0201": "50mW",  # 1/20 W
    "0402": "62.5mW",  # 1/16 W
    "0603": "100mW",  # 1/10 W
    "0805": "125mW",  # 1/8 W
    "1206": "250mW",  # 1/4 W
    "1210": "500mW",  # 1/2 W
    "2010": "750mW",  # 3/4 W
    "2512": "1W",
}

# Every size in R_POWER offers 1 ohm..10 Mohm at both grades (several offer
# more; this is the range common to all of them, so no size gets a value the
# datasheet does not list for it).
# Packaging type, which the RC_L datasheet couples to the case size — and the
# coupling is real, not cosmetic: RC2512FR-0710KL does not exist, RC2512FK-
# 0710KL does (checked against Yageo's own specsheet endpoint).
R_PACKING = {
    "0201": "R", "0402": "R", "0603": "R", "0805": "R",
    "1206": "R", "1210": "R", "2010": "K", "2512": "K",
}  # fmt: skip

R_DECADES = range(0, 7)
R_TOP = (100, 7)  # exactly 10 Mohm closes the range

TOLERANCES = {"F": "1%", "J": "5%"}


def vishay_code(mantissa, decade):
    """Vishay's fixed 4-character code: 3 significant digits, R/K/M as point."""
    for exp, letter in ((6, "M"), (3, "K"), (0, "R")):
        if decade >= exp:
            shift = decade - exp
            three = f"{mantissa:03d}"  # always 3 significant digits
            head, tail = three[: shift + 1], three[shift + 1 :]
            return f"{head}{letter}{tail}"
    raise ValueError(decade)


def resistor_values(tolerance):
    """(mantissa, decade) pairs, ascending. 1% adds E96 to E24's grid."""
    series = sorted(set(E24) | set(E96)) if tolerance == "F" else E24
    out = [(m, d) for d in R_DECADES for m in series]
    out.append(R_TOP)
    return out


def emit_resistors(size, verified):
    variant = f"R{size}"
    body = [
        header(
            f"Chip resistors, {size} — Yageo RC_L primary, Vishay CRCW e3 alternate.",
            GENERATED
            + "\n\n"
            + f"{len(resistor_values('F'))} values at +/-1% (E24 + E96) and "
            + f"{len(resistor_values('J'))} at +/-5% (E24),\n"
            + f"1 ohm to 10 Mohm. Rated power {R_POWER[size]}.",
        )
    ]
    for tol, tol_pct in TOLERANCES.items():
        for mantissa, decade in resistor_values(tol):
            token = ohm_token(mantissa, decade)
            mpn = f"RC{size}{tol}{R_PACKING[size]}-07{token}L"
            if verified.get(mpn) is False:
                continue
            literal = ohm_literal(mantissa, decade)
            body.append(
                f"pub part R_{token}_{tol}_{size}: ChipResistor<{literal}, {tol_pct}>[{variant}] {{\n"
                f'    primary {{ mfr: "Yageo", mpn: "{mpn}", footprint: CHIP_{size} }}\n'
                f'    alt {{ mfr: "Vishay", mpn: "CRCW{size}{vishay_code(mantissa, decade)}'
                f'{"FKED" if tol == "F" else "JNED"}" }}\n'
                f"}}\n"
            )
    return "\n".join(body)


# --------------------------------------------------------------------------
# Capacitors — Yageo CC series
#
# CC <size> <tolerance> <packing> <dielectric> <voltage> <process> <value>
#   tolerance J = +/-5% (C0G), K = +/-10% (X7R/X5R)
#   packing   R = paper/PE taping reel, 7 inch
#   voltage   4=4V 5=6.3V 6=10V 7=16V 8=25V 9=50V 0=100V A=200V Y=250V
#   process   BN for NP0, BB for class 2 (X7R/X5R)
#   value     EIA 3-digit code; R is the decimal point below 10 pF
# Verified against distributor listings: CC0402KRX7R7BB104 (100 nF 16 V X7R),
# CC0402JRNPO9BN101 (100 pF 50 V C0G), CC0603KRX5R6BB105 (1 uF 10 V X5R).
#
# WHICH parts exist is not derivable — it comes from the datasheets' own
# capacitance/voltage tables, frozen in tools/passive_data/yageo_mlcc.json. A
# combination absent from that file is not offered and is never emitted.
# --------------------------------------------------------------------------

C_VOLT_CODE = {
    4: "4", 6.3: "5", 10: "6", 16: "7", 25: "8", 50: "9", 100: "0", 200: "A", 250: "Y",
}  # fmt: skip

C_DIELECTRIC = {
    # name in the part number, process code, tolerance letter, tolerance spec
    "C0G": ("NPO", "BN", "J", "5%"),
    "X7R": ("X7R", "BB", "K", "10%"),
    "X5R": ("X5R", "BB", "K", "10%"),
}


def farad_token(farads):
    """`100n`, `4u7`, `15p`, `0p22` — the decimal point becomes the prefix."""
    for scale, letter in ((1e-6, "u"), (1e-9, "n"), (1e-12, "p")):
        if farads >= scale - 1e-18:
            v = farads / scale
            s = f"{v:.10g}"
            whole, _, frac = s.partition(".")
            return f"{whole}{letter}{frac}" if frac else f"{whole}{letter}"
    v = farads / 1e-12
    s = f"{v:.10g}".replace("0.", "")
    return f"0p{s}"


def farad_literal(farads):
    for scale, suffix in ((1e-6, "uF"), (1e-9, "nF"), (1e-12, "pF")):
        if farads >= scale - 1e-18:
            v = farads / scale
            return f"{v:.10g}{suffix}"
    return f"{farads / 1e-12:.10g}pF"


def eia_cap_code(farads):
    """EIA 3-digit: two significant digits + decade count; R is the point."""
    pf = farads / 1e-12
    if pf < 10:
        s = f"{pf:.10g}"
        whole, _, frac = s.partition(".")
        return f"{whole or '0'}R{frac}".ljust(3, "0")[:3] if frac else f"{whole}R0"
    digits_str = f"{pf:.10g}".replace(".", "")
    significant = digits_str.lstrip("0")[:2].ljust(2, "0")
    zeros = len(f"{int(round(pf))}") - 2
    return f"{significant}{zeros}"


def volt_token(volts):
    s = f"{volts:g}".replace(".", "V")
    return f"{s}V" if "V" not in s else s


def volt_literal(volts):
    return f"{volts:g}V"


def load_mlcc():
    import json

    path = pathlib.Path(__file__).resolve().parent / "passive_data" / "yageo_mlcc.json"
    return json.loads(path.read_text())["available"]


def emit_capacitors(size, available, alternates, samsung, verified):
    variant = f"C{size}"
    rows, count = [], 0
    for key in sorted(available):
        sz, volts, diel = key.split("|")
        if sz != size:
            continue
        volts = float(volts)
        name, process, tol_letter, tol_spec = C_DIELECTRIC[diel]
        for farads in available[key]:
            mpn = (
                f"CC{size}{tol_letter}R{name}{C_VOLT_CODE[volts]}{process}{eia_cap_code(farads)}"
            )
            # The datasheet tables say what the series covers; the specsheet
            # endpoint says what actually exists. Disagreements go the safe
            # way: a part Yageo will not confirm is not a part we ship.
            if verified.get(mpn) is False:
                continue
            token = farad_token(farads)
            part = f"C_{token}_{volt_token(volts)}_{diel}_{size}"
            entries = list(alternates.get(part, []))
            samsung_mpn = samsung.get(f"{size}|{volts:g}|{diel}|{farads:.6g}")
            if samsung_mpn and not any(m == "Samsung" for m, _ in entries):
                entries.append(("Samsung", samsung_mpn))
            alts = "".join(f'    alt {{ mfr: "{mfr}", mpn: "{mpn}" }}\n' for mfr, mpn in entries)
            rows.append(
                f"pub part {part}: MLCC<{farad_literal(farads)}, {volt_literal(volts)}, {tol_spec}>[{variant}] {{\n"
                f'    primary {{ mfr: "Yageo", mpn: "{mpn}", footprint: CHIP_{size} }}\n'
                f"{alts}"
                f"}}\n"
            )
            count += 1
    body = [
        header(
            f"MLCC capacitors, {size} — Yageo CC series.",
            GENERATED
            + "\n\n"
            + f"{count} parts: every (dielectric, rated voltage, capacitance) Yageo's\n"
            + "own datasheet tables list for this size, and no combination they do not.",
        )
    ]
    return "\n".join(body + rows)


def main():
    if not OUT.parent.parent.is_dir():
        sys.exit("run from the repository root")
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "pads.cohdl").write_text(emit_pads())
    (OUT / "footprints.cohdl").write_text(emit_footprints())
    written = 2
    verified = load_verified()
    for size in R_POWER:
        (OUT / f"resistors_{size}.cohdl").write_text(emit_resistors(size, verified))
        written += 1
    available = load_mlcc()
    samsung = load_samsung()
    cap_sizes = sorted({k.split("|")[0] for k in available})
    (OUT / "devices.cohdl").write_text(emit_devices(cap_sizes))
    written += 1
    for size in cap_sizes:
        (OUT / f"capacitors_{size}.cohdl").write_text(
            emit_capacitors(size, available, VERIFIED_ALTERNATES, samsung, verified)
        )
        written += 1
    print(f"wrote {written} files under {OUT}")


if __name__ == "__main__":
    main()
